# Synthpix Configuration YAML File
# ================================
# This is the default configuration file of synthpix. It contains the project's parameters and settings.
# To learn more about choosing these parameters to change Synthpix's behaviour, see the project's "README.md".

# Dataset parameters
seed: 0
batch_size: 1
flow_fields_per_batch: 1
batches_per_flow_batch: 1
randomize: false
loop: true
identifiable_flow: false
device_ids: [0]

# Image rasterization parameters
image_shape: [1024, 1024]
dt: 1
seeding_density_range: [0.03, 0.04]
p_hide_img1: 0.0001
p_hide_img2: 0.0001
diameter_ranges: [[1.5, 2.5]]
diameter_var: 0.03
intensity_ranges: [[150, 230]]
intensity_var: 0.01
rho_ranges: [[-0.1, 0.1]]
rho_var: 0.1
noise_uniform: 0.001
noise_gaussian_mean: 0.01
noise_gaussian_std: 0.001

# Physical Sizing
velocities_per_pixel: 1.0
resolution: 1

# Flow field parameters
flow_field_size: [1024, 1024]
img_offset: [0, 0]
min_speed_x: 0
max_speed_x: 0
min_speed_y: 0
max_speed_y: 0
output_units: "pixels"

# Flows files
file_list:
  - /shared/fluids/fluids-estimation/eye_candies_main
scheduler_class: ".mat"
